# Generated by Django 5.0.2 on 2024-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='category',
            field=models.CharField(choices=[('logement', 'Logement'), ('stage', 'Stage'), ('évenClub', 'ÉvenClub'), ('évenSocial', 'ÉvenSocial'), ('transport', 'Transport')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('logement', 'Logement'), ('stage', 'Stage'), ('évenClub', 'ÉvenClub'), ('évenSocial', 'ÉvenSocial'), ('transport', 'Transport')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='category',
            field=models.CharField(choices=[('logement', 'Logement'), ('stage', 'Stage'), ('évenClub', 'ÉvenClub'), ('évenSocial', 'ÉvenSocial'), ('transport', 'Transport')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='category',
            field=models.CharField(choices=[('logement', 'Logement'), ('stage', 'Stage'), ('évenClub', 'ÉvenClub'), ('évenSocial', 'ÉvenSocial'), ('transport', 'Transport')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='category',
            field=models.CharField(choices=[('logement', 'Logement'), ('stage', 'Stage'), ('évenClub', 'ÉvenClub'), ('évenSocial', 'ÉvenSocial'), ('transport', 'Transport')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='évenclub',
            name='category',
            field=models.CharField(choices=[('logement', 'Logement'), ('stage', 'Stage'), ('évenClub', 'ÉvenClub'), ('évenSocial', 'ÉvenSocial'), ('transport', 'Transport')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='évensocial',
            name='category',
            field=models.CharField(choices=[('logement', 'Logement'), ('stage', 'Stage'), ('évenClub', 'ÉvenClub'), ('évenSocial', 'ÉvenSocial'), ('transport', 'Transport')], default='', max_length=50),
        ),
    ]
