# Generated by Django 5.0.2 on 2024-05-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_logement_category_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='évenclub',
            name='category',
        ),
        migrations.RemoveField(
            model_name='évensocial',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='Catg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
